name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Install `poetry` 
        run: |
          pipx install poetry
          poetry --version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install package
        run: |
          poetry install
      - name: Run linter
        run: |
          poetry run flake8 torch_topological
      - name: Run tests
        run: |
          poetry run pytest
